### PR TITLE
ci: deploy to firebase

### PR DESCRIPTION
**Pull request by helder-moreira**

### CODE REVIEW

**Comment by helder-moreira** [comment]
> @helder-moreira PR seems fine but before we merge we'll need to coordinate our deployment strategy a bit. Currently the server is built in the `dist` folder but `npm run build` builds into the `build` folder. So once this hosting strategy is live we can remove the `dist` folder from the repository to avoid confusion

@drewstaylor I have checked the Netlify deployment config before creating the PR.
image
According to it, it's the build directory that is being used.

**Comment by drewstaylor** [comment]
@helder-moreira Interesting, I guess `dist` is only needed for PR previews (otherwise my code doesn't update). Is it safe to merge this in main branch now or do we need to wait for migrating anything from Netlify?

**Comment by helder-moreira** [comment]
> @helder-moreira Actually my code doesn't update on the server if I don't build to `dist`, are we sure Netlify docker isn't copying everything over and actually serving from `dist`?

That is strange. How do you deploy it? Do you just wait for netlify comment on PR?


> Also, is it safe to merge this in main branch now or do we need to wait for migrating anything from Netlify?

No need to wait. They will both co-exist until we make the change in DNS.

**Comment by drewstaylor** [comment]
> That is strange. How do you deploy it? Do you just wait for netlify comment on PR?
Some sort of github action. If I merge to main branch it updates the prod server and for PRs it's as you say

**Comment by drewstaylor** [comment]
@helder-moreira should we be worried about deploy action failing (https://github.com/archway-network/archway-docs/runs/6260937325?check_suite_focus=true), or is that just because the new the firebase hosting doesn't exist yet?

**Comment by helder-moreira** [comment]
@drewstaylor my mistake. I will push a quick fix to `main`.

**Comment by drewstaylor** [comment]
Awesome, thanks @helder-moreira

**Pull request merged**
