### PR TITLE
Implement rebranding changes

### PR DESCRIPTION
**Pull request by macku99**

### CODE REVIEW

**Comment by drewstaylor** [comment]
This will be merged later today, in order to be ready for tomorrow AM. Just doing final review atm.

**Comment by drewstaylor** [comment]
Current bugs list:
- Mobile missing dark / light mode toggle
- Docs side menu unscrollable on Windows and Android

**Review by drewstaylor — CHANGES_REQUESTED** [review]
Please add back the dark / light mode toggle button into the mobile accordion menu. I fixed the other bug

**Comment by drewstaylor** [comment]
To be fixed:
- Mobile missing dark / light mode toggle
- Docs side menu unscrollable on mobile devices when multiple categories opened

**Review by aelesbao — APPROVED** [review]

**Pull request merged**
