### PR TITLE
Updates tutorial guides, and developer content for CLI v1.2.1

### PR DESCRIPTION
**Pull request by drewstaylor**
### In this PR:
- Changes to docs left sidebar navigation and menu items to make it easier to find CLI API docs
- Tutorials updated with new deployment workflow
- Legacy flag `--dry-run` removed from all docs

### Effected pages:
- [Home page](https://docs-archway--pr97-develop-zb5emptn.web.app/)
- My First dApp guide ([page 1](https://docs-archway--pr97-develop-zb5emptn.web.app/docs/create/guides/my-first-dapp/faucet), [page 2](https://docs-archway--pr97-develop-zb5emptn.web.app/docs/create/guides/my-first-dapp/wasm), [page 3](https://docs-archway--pr97-develop-zb5emptn.web.app/docs/create/guides/my-first-dapp/deploy))
- [Building with NFTs guide](https://docs-archway--pr97-develop-zb5emptn.web.app/docs/create/guides/nft-project/deploy)
- [Wallet doc](https://docs-archway--pr97-develop-zb5emptn.web.app/docs/participate/wallet)

***
The only changes to the Home page and Wallet doc are the URL links to the CLI API docs (new link structure)

### CODE REVIEW

**Comment by drewstaylor** [comment]
@aelesbao This PR review should be pretty straight forward, but let me know if you want anything changed

**Comment by drewstaylor** [comment]
TODO: 

- Add archwayd section to Developers -> CLI -> Introduction
- Change "API Docs" to Developer CLI

**Review by aelesbao — COMMENTED** [review]
Please change the command `archway deploy -dry-run` in the WASM instructions to `archway build`. The `--dry-run` flag is a bit misleading since what it does is only build the contract.

**Comment by drewstaylor** [comment]
> Please change the command `archway deploy -dry-run` in the WASM instructions to `archway build`. The `--dry-run` flag is a bit misleading since what it does is only build the contract.

Does it still build a WASM output file in the artifacts folder as it used to with `--dry-run`?

**Comment by drewstaylor** [comment]
Legacy flag `--dry-run` now removed from all docs

**Review by aelesbao — APPROVED** [review]

**Pull request merged**
